---
- hosts: all
  vars_files:
    - vars.yml
  tasks:
    # INSTALAR PYTHON Y LIBRERIAS
    - name: Instalar Python y librerias
      apt:
        pkg:
          - python3
          - python3-dev
          - python3-pip
          - python3-venv
          - python3-psycopg2
        state: present
        update_cache: yes

    # INSTALAR Y CONFIGURAR BASE DE DATOS
    - name: Instalar Postgresql
      apt:
        name: postgresql
        state: present
        update_cache: yes

    - name: Crear base de datos ckan_default
      remote_user: root
      become: true
      become_user: postgres
      postgresql_db:
        name: ckan_default
        encoding: UTF-8
        state: present

    - name: Crear usuario ckan_default
      postgresql_user:
        db: ckan_default
        name: "{{ckan_db_user}}"
        role_attr_flags: NOSUPERUSER,NOCREATEDB,NOCREATEROLE
        password: "{{ckan_db_password}}"
        state: present
      become: true
      become_user: postgres

    - name: Crear base de datos datastore_default
      postgresql_db:
        name: datastore_default
        owner: ckan_default
        encoding: UTF-8
        state: present
      become: true
      become_user: postgres

    - name: Crear usuario datastore_default
      postgresql_user:
        name: "{{datastore_db_user}}"
        role_attr_flags: NOSUPERUSER,NOCREATEDB,NOCREATEROLE
        password: "{{datastore_db_password}}"
        state: present
      become: true
      become_user: postgres

    - name: Crear base de datos drupal
      postgresql_db:
        name: drupal
        encoding: UTF-8
        state: present
      become: true
      become_user: postgres

    - name: Crear usuario drupal
      postgresql_user:
        db: drupal
        name: "{{drupal_db_user}}"
        role_attr_flags: NOSUPERUSER,NOCREATEDB,NOCREATEROLE
        password: "{{drupal_db_password}}"
        state: present
      become: true
      become_user: postgres

    # INSTALAR Y CONFIGURAR CKAN
    - name: Eliminar directorios existentes
      shell: rm -rf /usr/lib/ckan
      ignore_errors: yes

    - name: Instalar las dependencias de CKAN
      apt:
        pkg:
          - git
          - libpq5
          - redis-server
          - nginx
          - supervisor
        state: present
        update_cache: yes
    
    - name: Instalar el paquete oficial de CKAN 2.9
      apt:
        deb: http://packaging.ckan.org/python-ckan_2.9-py3-focal_amd64.deb
    
    - name: Implantar CKAN.INI por defecto
      copy:
        src: config/ckan.ini
        dest: /etc/ckan/default/ckan.ini
        force: yes
      
    # INSTALAR Y CONFIGURAR SOLR
    - name: Instalar Apache Solr
      apt:
        name: solr-tomcat
        state: present

    - name: Renombrar schema.xml a schema.xml.bak
      shell: mv /etc/solr/conf/schema.xml /etc/solr/conf/schema.xml.bak

    - name: Añadir schema.xml en Solr con enlace simbólico
      file:
        src: "/usr/lib/ckan/default/src/ckan/ckan/config/solr/schema.xml"
        dest: "/etc/solr/conf/schema.xml"
        state: link
    
    # CONFIGURAR TOMCAT
    - name: Configurar puerto 8983 en Tomcat
      copy:
        src: config/server.xml
        dest: /etc/tomcat9/server.xml

    # INSTALAR EXTENSIONES DE CKAN
    # To do

    # IMPORTAR BASE DE DATOS DE REFERENCIA A CKAN
    # To do

    # INSTALAR DRUPAL Y SUS DEPENDENCIAS
    - name: Instalar servidor Apache
      apt:
        name: apache2
        state: present
    
    - name: Editar archivo ports.conf
      copy:
        src: config/ports.conf
        dest: /etc/apache2/ports.conf
        force: yes

    - name: Editar 000-default.conf
      copy:
        src: config/000-default.conf
        dest: /etc/apache2/sites-available/000-default.conf
        force: yes

    - name: Instalar PHP 7.4
      apt:
        pkg:
          - php7.4
          - php7.4-dev
          - php7.4-common
          - php7.4-zip
          - php7.4-curl
          - php7.4-json
          - php7.4-xml
          - php7.4-mbstring
          - php7.4-gd
        state: present

    - name: Instalar Composer 2
      shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin/ --filename=composer
        
    # TAREAS DE LIMPIEZA
    - name: Eliminar paquetes en desuso de la caché
      apt:
        autoclean: yes

    - name: Eliminar dependencias no requeridas
      apt:
        autoremove: yes

    # INICIALIZAR BASE DE DATOS CKAN
    - name: Borrar base de datos CKAN
      shell: /usr/lib/ckan/default/bin/ckan --config=/etc/ckan/default/ckan.ini db clean --yes
      become_user: vagrant

    - name: Inicializar base de datos CKAN
      shell: /usr/lib/ckan/default/bin/ckan --config=/etc/ckan/default/ckan.ini db init
      become_user: vagrant

    # APLICAR PERMISOS
    - name: Ajustes de permisos en CKAN
      shell: chown -R www-data:www-data /var/lib/ckan
      become: yes
      become_user: root

    - name: Ajustes de permisos en CKAN
      shell: chmod -R 777 /var/lib/ckan
      become: yes
      become_user: root

    # REFRESAR SERVICIOS
    - name: Reiniciar Solr
      service:
        name: tomcat9
        state: restarted

    - name: Reiniciar servidor Apache
      service:
        name: apache2
        state: restarted
    
    - name: Recargar supervisor
      become: yes
      become_user: root
      shell: supervisorctl reload
      ignore_errors: yes

    - name: Reiniciar servidor Nginx
      service:
        name: nginx
        state: restarted

    # IMPORTAR CLAVES SSH
    - name: Importar directorio de ssh keys
      copy:
        src: "~/.ssh"
        dest: "~/.ssh"
      ignore_errors: yes

    # CREAR SYMLINK PARA EL COMANDO CKAN
    - name: Crear symlink para comando ckan
      become: yes
      file:
        src: "/usr/lib/ckan/default/bin/ckan"
        dest: "/usr/bin/ckan"
        state: link
      ignore_errors: yes

    # CREAR USUARIO SYSADMIN
    - name: Crear usuario sysadmin de CKAN
      expect:
        command: ckan -c /etc/ckan/default/ckan.ini sysadmin add "{{sysadmin_user}}" email="{{sysadmin_email}}" name="{{sysadmin_user}}" password="{{sysadmin_password}}"
        responses:
          Question:
            - Y
      ignore_errors: yes